version: '3.8'
services:
  app:
    build: ./docker/php
    volumes:
      - .:/var/www
    depends_on:
    - mailhog

  nginx:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - app

  db:
    image: mysql:8.0
    tty: true
    environment: 
      MYSQL_DATABASE: ec-site
      MYSQL_USER: db-user
      MYSQL_PASSWORD: db-pass
      MYSQL_ROOT_PASSWORD: db-pass
      TZ: 'Asia/Tokyo' 
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:  
      - ec_site_volume:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    tty: true
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: db
      PMA_USER: db-user
      PMA_PASSWORD: db-pass
    links:
      - db
    ports:
      - 3000:80
    
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
  
volumes:
  ec_site_volume: